select JOB_TITLE || ' '|| MIN_SALARY || ' '|| MAX_SALARY
from jobs
WHERE job_title like 'P%';


SELECT STUDENT_ID, FIRST_NAME, STUDENT_REG_YEAR as ADMISSION
FROM AD_STUDENT_DETAILS;

SELECT *
FROM AD_COURSE_DETAILS;

SELECT STUDENT_ID
      , FIRST_NAME
      ,STUDENT_REG_YEAR+2 "COUSRE EXPIRY"
FROM AD_STUDENT_DETAILS;

DESCRIBE AD_COURSE_DETAILS;

DESCRIBE AD_STUDENT_DETAILS;

SELECT STUDENT_ID
      ,FIRST_NAME
      ,PARENT_ID
      ,STUDENT_REG_YEAR AS REGISTRATION
FROM AD_STUDENT_DETAILS;

DESC AD_EXAM_DETAILS;

SELECT DISTINCT NAME
FROM AD_EXAM_DETAILS;

SELECT STUDENT_ID "Student #"
      ,FIRST_NAME "Student"
      ,PARENT_ID "Parent Infromation"
      ,STUDENT_REG_YEAR "Registered ON"
FROM AD_STUDENT_DETAILS;

SELECT COURSE_ID || ', ' ||COURSE_NAME AS "Course ID and Title"
FROM AD_COURSE_DETAILS;

DESC AD_EXAM_DETAILS;

SELECT EXAM_ID || ', ' || EXAM_TYPE || ', ' || START_DATE  || ', ' || NAME AS THE_OUTPUT
FROM AD_EXAM_DETAILS;


